services:
  postgres_db:
    image: postgres:17-alpine
    container_name: local
    restart: always
    environment:
      - POSTGRES_USER=swan
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

    ports:
      - '5432:5432'
